apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k6k983p9m-python 
  janus-idp.io/tekton: k6k983p9m-python
  backstage.io/kubernetes-id: k6k983p9m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k6k983p9m-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  