apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k6k983p9m-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d0b1721ac3682d472307d11dee124db3e1787588@sha256:7c4e88c78519e4ed2ffd83205c53236dd715529446a8572dbfd0b1cbfe56ae9c
          name: container-image
